INSERT INTO Price (vehicle_Id, currency, price) VALUES (1,'USD', 10000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (2,'USD', 11000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (3,'USD', 12000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (4,'USD', 13000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (5,'USD', 14000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (6,'USD', 15000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (7,'USD', 16000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (8,'USD', 17000);
INSERT INTO Price (vehicle_Id, currency, price) VALUES (9,'USD', 18000);
